#!/usr/bin/env python3

import csv
from playwright.sync_api import sync_playwright
from bs4 import BeautifulSoup
from requests.auth import HTTPBasicAuth


with sync_playwright() as p:
    browser = p.chromium.launch(headless=False, slow_mo=500)
    page = browser.new_page()

    #Update to Login to Github - user & password obfuscation in Powershell
    page.goto('https://github.com/login')
    page.fill('input#login_field', 'USERNAME')
    page.fill('input#password', 'PASSWORD')
    page.click('input[type=submit]')

    #Create CSV file
    csv_file = open('C:\\Users\\(Sherwin ID)\\OneDrive - Sherwin-Williams\\Desktop\\GHAS_settings.csv', 'w', newline='')
    csv_writer = csv.writer(csv_file)
    csv_writer.writerow(['Repository', 'Dependabot', 'Code Scanning', 'Secret Scanning'])

    #Redirect Into Github Security Coverage
    for page_number in range(1,2):
        page_url = f'https://github.com/orgs/sherwin-williams-co/security/coverage?page={page_number}'
        page.goto(page_url)

        page.click('button[type=submit]') 
        page.is_visible('#coverage-data')
 
        html = page.inner_html('#coverage-data')
        soup = BeautifulSoup(html, 'html.parser')

    # Seperate Data by Repository & Define Function
        page.is_visible('#coverage-data')
        repository_divs = soup.find_all('div', class_='flex-1 d-flex flex-wrap')

        for div in repository_divs:
            repository_name = div.find('a', class_='Link--primary text-bold d-block').get_text(strip=True)
    
            dependabot_setup = div.find('span', text='Dependabot').find_next_sibling('span').get_text(strip=True)
            codescanning_element = div.find('span', text='Code scanning')
            if codescanning_element:
                codescanning_setup= codescanning_element.find_next('span').get_text(strip=True)
            else:
                codescanning_setup= "Not Found"
            secret_setup = div.find('span', text='Secret scanning').find_next_sibling('span').get_text(strip=True)

            csv_writer.writerow([repository_name, dependabot_setup, codescanning_setup, secret_setup])

csv_file.close()

